### ISSUE TITLE
Apply better error handling on POST /operations

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#110]
We are currently handling any type of error in the same way in the handler for `POST /operations` and return `400` even if the problem be something other than problem in user provided input:

https://github.com/BrightID/BrightID-Node/blob/bd85cdd6afef241cfb831411af937b98ba496727/web_services/foxx/brightid5/index.js#L68-L71

This should be improved and `400` only be returned if the user input has a problem.

**Comment by siftal** [comment]
It's done
https://github.com/BrightID/BrightID-Node/commit/450af03fb7742d9efabac03b32e25b8693d1959c
