### ISSUE TITLE
Let user re-link and re-order their contextids

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#112]
If a user re-links a contexid that was used before, but only by them, it should be allowed. It should update the timestamp on that contextid and bring it to the front of the array returned by `/verifications`;  `unique` should be `true` for that contextid.

**Comment by abramsymons** [comment]
We are allowing to link the last contextId again now.
But allowing to use old ones will cause loops in history for the contract implement to publish verifications onchain, so apps can not  traverse history to find all the ids used by the user.

**Comment by adamstallard** [comment]
> We are allowing to link the last contextId again now.
> But allowing to use old ones will cause loops in history for the contract implement to publish verifications onchain, so apps can not traverse history to find all the ids used by the user.

Thanks for catching this bug! We should fix the recommended smart contract template to support this.  I'll add a comment to this issue in BrightID-SmartContract https://github.com/BrightID/BrightID-SmartContract/issues/8

**Comment by abramsymons** [comment]
resolved by:
https://github.com/BrightID/BrightID-Node/commit/b80ec55182deba32bef1e8233e54b7fed6385419

**Comment by abramsymons** [comment]
resolved by:
https://github.com/BrightID/BrightID-Node/commit/b80ec55182deba32bef1e8233e54b7fed6385419
