### ISSUE TITLE
Allow contexts to define multiple verifications they care about

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#121]
from @adamstallard : 

A context should be able to choose to support multiple verifications at once. Imagine if you query a user like /verifications/Gitcoin/1234 and you get output that says "verifications":["joined_call","brightid","connected_to_seed"]  or if they only got "joined_call" then "verifications":["joined_call"]

We'd have to return error in the case of no verifications (to avoid breaking backwards compatibility), but if there is at least one, we can return an array.

**Comment by adamstallard** [comment]
Also return `verifications[]` instead of `score` in the `/users/` endpoint

**Comment by abramsymons** [comment]
The approach described in #139 is more flexible approach for apps.
