### ISSUE TITLE
/testblocks API endpoint for testing new app integrations

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#127]
There should be special test endpoints to

1.  Add and remove the "sponsored" attribute
2.  Add and remove verifications
3.  Remove contextids. (Remove links so that the contextids are "not found.")

Every application that has integrated with BrightID so far would have benefited from this.

**See [this comment](https://github.com/BrightID/BrightID-Node/issues/127#issuecomment-730549607) about how to implement it**

**Comment by adamstallard** [comment]
These should use operations to share information with other nodes that work with the same contexts and should be available in both the test network and the main network.

This is easier and cleaner than using ArangoDB GUI to make manual edits and somehow disabling consensus so these tests don't get propagated.

**Comment by abramsymons** [comment]
I feel there are lots of questions that should be answered if we want to enable apps developers doing such test operations on the main network.
It will be much simpler to do tests using the test client connected to the test network.
It certainly helps if we have a command line brightid client that enable developers to do above listed tasks on brightids they own by sending operations defined for the test network.
Test client can enable users export their brightid private key and then they can import that into the command line client and send all of the operations including ones doing above tasks to the test network.

**Comment by adamstallard** [comment]
@abramsymons 

I thought more about what would be the simplest solution for testers. The advantage to the testnet is it's easy to create new test users on debug BrightID. We could probably change debug BrightID to allow it to connect to mainnet, so I created a section for what would be different with mainnet.

We could create a `testApiKey` setting in a context. Testers just need to supply that as a parameter to each call to the test methods.
(This isn't needed on testnet, but it would be on mainnet.)

The test methods wouldn't create any operations. We'd have those test methods update the database just on the node that receives the requests.

Here are some test endpoints/methods I suggest

`PUT /verifications/<context>/<contextid>` Update verifications for a user. This is allowed as long as the user is only linked to the one context supplied in the url.
`DELETE /verifications/<context>/<contextid>` Delete all verifications from a user. This is allowed as long as the user is only linked to the one context supplied in the url.
`DELETE /contextids/<context>/<contextid>` Delete a contextid from whichever user has it.
`DELETE /sponsorships/<context>/<contextid>` Delete the sponsorship from a user. This is allowed as long as the user is only linked to the one context supplied in the url.

These work because a user linked only to a new context being tested must be a test user.

Burning through sponsorships on testnet shouldn't be an issue. If it becomes an issue we could have a test setting for sp_updater to fake assign an additional 10 billion sponsorships to every app.

### Differences on mainnet

If we make these functions available on mainnet, the testers would have to be ok with burning a few real sponsorships.

The `testApiKey` setting should be deleted by the node operator when the context goes live, as well as any verifications and contextids created during testing. Test methods wouldn't be available for a new app in an existing context, because that context is already live and the `testApiKey` wouldn't exist anymore.

**Comment by adamstallard** [comment]
Here's how to implement it.

Add a new endpoint : `/testblock` that allows someone to add or remove a block on a verification, sponsorship, or link to any user, identified by contextId. To use the endpoint, you need to know the private `testingKey` set in the app's settings.

A `testblock` means that the functionality (being verified, sponsored, or linked) is temporarily blocked until the test block is removed (with the `DELETE` method). In the case of sponsoring and linking, it can also be removed by going through the regular sponsor or link steps again, but there is no way to "re-verify," so re-verifying is only done by removing the block.

Add a testblock to a user
```
PUT /testblock/<app>/verification/<contextid>?testingKey=<base64>
PUT /testblock/<app>/sponsorship/<contextid>?testingKey=<base64>
PUT /testblock/<app>/link/<contextid>?testingKey=<base64>
```

Remove a testblock from a user
```
DELETE /testblock/<app>/verification/<contextid>?testingKey=<base64>
DELETE /testblock/<app>/sponsorship/<contextid>?testingKey=<base64>
DELETE /testblock/<app>/link/<contextid>?testingKey=<base64>
```

These methods will allow app creators to see how users appear to the app with all combinations of verified, sponsored, and linked. 

It should be available on both BrightID testnet and mainnet.

**Comment by adamstallard** [comment]
We might want another endpoint for test/private networks only to add a verification to a user, so that testing can be automated with fake users.

**Comment by adamstallard** [comment]
> 
> 
> I feel there are lots of questions that should be answered if we want to enable apps developers doing such test operations on the main network.
> It will be much simpler to do tests using the test client connected to the test network.
> It certainly helps if we have a command line brightid client that enable developers to do above listed tasks on brightids they own by sending operations defined for the test network.
> Test client can enable users export their brightid private key and then they can import that into the command line client and send all of the operations including ones doing above tasks to the test network.

As discussed in keybase, we should implement an sdk to do a lot of data manipulation functions on a private node or test net. This is for another issue.
