### ISSUE TITLE
Don't allow a trusted connection to be used for recovery if it is too new

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#128]
Don't allow users to recover with a trusted connection that was set in the last week (unless it was one of the original ones).

This strengthens security in the case of robbery, bribery or theft.

**Comment by abramsymons** [comment]
related to #140

With having history of connections, `Set Signing Key` operation can allow connections that had `recovery` level in the past week to participate in recovering process. We can also prevent connections that their level set to `recovery` in the past week from participating in recovering process.
