### ISSUE TITLE
Allow a user to remove a trusted connection

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#130]
You can remove a trusted connection at any time, but a remove trusted connection operation should take one week to take effect to protect against takeover.

**Comment by abramsymons** [comment]
related to #140 
With having history of connections, `Set Signing Key` operation can allow connections that had `recovery` level in the past week to participate in recovering process. We can also prevent connections that their level set to `recovery` in the past week from participating in recovering process.

**Comment by TripleSpeeder** [comment]
We should also think about how this can be managed/visualized on the UI.
