### ISSUE TITLE
Enable apps getting customized verification

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#139]
Currently apps can only use a single verification configured on the context they use.

We can add a new parameter to the `GET /verifications/{context}/{contextId}` to enable apps pass an `expression` like:
`((SeedConnected and SeedConnected.timestamp > 1604130920901) or SeedConnectedWithFriend) and (Yekta and Yekta.rank >= 3`
to this endpoint and get customized verification from the node.

The `expression` should be encoded using `encodeURIComponent`.
The node decode the parameter using `decodeURIComponent` and can use libs like [expr-eval](https://github.com/silentmatt/expr-eval#evaluatevariables-object) to securely evaluate the `expression` by passing the users' verifications.
The node can also calculate the sha256 hash of the expression and include first 5 bytes of that in the message that signed by the node and also the response object as `expressionHash` to enable apps verify the expression while they are verifying the sig provided by the node.

**Comment by abramsymons** [comment]
We can remove `verification` from `contexts` documents  in database and use `BrightID` as default value for `expression`, if such a flexible verification added to the node.

**Comment by adamstallard** [comment]
> 
> 
> Currently apps can only use a single verification configured on the context they use.
> 
> We can add a new parameter to the `GET /verifications/{context}/{contextId}` to enable apps pass an `expression` like:
> `((SeedConnected and SeedConnected.timestamp > 1604130920901) or SeedConnectedWithFriend) and (Yekta and Yekta.rank >= 3`
> to this endpoint and get customized verification from the node.
> 
> The `expression` should be encoded using `encodeURIComponent`.
> The node decode the parameter using `decodeURIComponent` and can use libs like [expr-eval](https://github.com/silentmatt/expr-eval#evaluatevariables-object) to securely evaluate the `expression` by passing the users' verifications.
> The node can also calculate the sha256 hash of the expression and include first 5 bytes of that in the message that signed by the node and also the response object as `expressionHash` to enable apps verify the expression while they are verifying the sig provided by the node.

Can a smart contract verify this?

**Comment by abramsymons** [comment]
> Can a smart contract verify this?

Sure they can verify that in this way:
https://github.com/BrightID/BrightID-SmartContract/blob/reuse-context-id/v4/BrightID.sol#L79

**Comment by adamstallard** [comment]
>The node can also calculate the sha256 hash of the expression and include first 5 bytes of that in the message that signed by the node
Why did you decide to use only the first 5 bytes of the signed message. Are you sure this offers the same security against preimage attacks?

**Comment by abramsymons** [comment]
> > The node can also calculate the sha256 hash of the expression and include first 5 bytes of that in the message that signed by the node
> 
> @abramsymons Why did you decide to use only the first 5 bytes of the hash of the expression instead of the full 32 bytes? Are you sure this offers the same security against preimage attacks?

We changed that and we are  using the full 32 bytes now. You can see that in return value of this query:
http://test.brightid.org/brightid/v5/verifications/idchain/0xfef95f2b363d11c1a3c62745e50cced96277b2e8?signed=eth&timestamp=seconds&verification=Yekta%20and%20SeedConnected
