### ISSUE TITLE
Allow reporting someone only if reported user already know the reporter or requested the connection

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#141]
To prevent abusing the reporting routine, we should prevent users from reporting someone that never had connection with them.
The only problem is that how we should enable users to report `spammer`s, because they do not have connection with them?

To solve this problem we can add a sig from the connection requester to be included by the reporter to verify that request come from the reported user.

**Comment by siftal** [comment]
Now "requestProof"  is added to the connections so the verification providers can check if the reported user either already knows the reporter or requested the connection, and apply a penalty in one of the above situations.
So we apply all the reports and the verification providers can decide about the penalties.
