### ISSUE TITLE
Making signing keys portable (usable on other devices)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#155]
We could do this through delegated signing key pairs.

You could create delegate key pairs for your signing key pair so you can use BrightID from multiple devices or apps. If you go through social recovery to get a new master key pair, it would revoke all your delegates.  You could also revoke them individually.

This is a more secure model than attempting to transfer around the master key pair

To make brightid keys portable doesn't have to involve transmitting the keys to another device (which could be tricky to do securely), but instead generating a new (delegated) signing key pair and letting BrightID nodes know that you've authorized it (by signing the public key of the new key pair with your master signing key pair).  One pair of keys could be the master key pair that can be used to revoke others. (If you've added a device, you can remove it.)  If social recovery is invoked, all key pairs are invalidated and a new master key pair is installed.  You'd have to reconnect all your devices after that.

**Comment by Motanovici** [comment]
Hello everybody! I would like to help with this issue.

**Comment by bitsikka** [comment]
@adamstallard 

As an alternative, seems open source hardware - Status [keycard](https://twitter.com/Keycard_) can be used 🤔 

here is what is being worked for Status-React

https://github.com/status-im/status-react/pull/11526

**Comment by adamstallard** [comment]
> generating a new (delegated) signing key pair and letting BrightID nodes know that you've authorized it (by signing the public key of the new key pair with your **_master_** signing key pair). **_One pair of keys could be the master key pair that can be used to revoke others._** (If you've added a device, you can remove it.) If social recovery is invoked, all key pairs are invalidated and a new master key pair is installed. You'd have to reconnect all your devices after that.

I want to go against what I wrote in the original description about "master" and "delegated" signing keys. It would be nice if all signing keys were on the same level. There wouldn't be a notion of a master key or a delegated key--just signing keys.

Social recovery would still reset the signing keys back to just one (new one).

I think this will make it easier to use a second device as a recovery device if you lose the first one--or just to transfer to another device without using social recovery.

I was probably thinking about some case where a delegated device or app creates more signing keys without the user knowing, but there are ways to alert the user about this, and if something seems suspicious, the safest option is to choose one device, and revoke all other signing keys and start over from there.
