### ISSUE TITLE
Automate transfer links under a context between nodes

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#156]
BrightID nodes should provide a way to enable automatic transfer of links from one node to another.
[This document](https://github.com/BrightID/BrightID-Node/wiki/Adding-a-pre-existing-context-to-your-node) describes the process that should be followed to transfer links of a pre-existing context to a node.
This process can be automated if node API provide an endpoint to enable authorized new node operators get links from a node having them.
A one time passcode can be added to the context document in `contexts` collection that can be used for authorization.
This one time passcode should be automatically removed from context after being used by getting dump to enforce one time nature of that.
Also a script can be implemented to use that one time passcode to get the dump and restore it to the target node database following the process described in above document.

**Comment by adamstallard** [comment]
I think this automatic transfer should also transfer
`sponsorshipPrivateKey` and `testingKey` from the `apps` document associated with the app
and also the document from `contexts` associated with the app

**Comment by siftal** [comment]
> I think this automatic transfer should also transfer
> `sponsorPrivateKey` and `testingKey` from the `apps` document associated with the app. (Maybe it could just transfer the whole document.)
> and also the document from `contexts` associated with the app (including the `linkAESKey`)

Contexts can have multiple apps and context owner may not be the app owner, so sponsorPrivateKey should be shared by the app owner to the new node admin.  New node operator can set sponsor private key or testing key using following commands:
$ python3 admin.py set-sponsor-private-key --app app --key privatekey
$ python3 admin.py set-testing-key --app app --key privatekey

**Comment by abramsymons** [comment]
[This document](https://github.com/BrightID/BrightID-Node/wiki/Import-a-context-from-a-node-into-another-one) describes how `brightidcli` can be used to import a context from a node into another one.
