### ISSUE TITLE
Allow sponsoring before linking

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#159]
To improve the user experience, we can sponsor a contextid before linking it.  If a contextid is sponsored that isn't linked, we can [store it with a short TTL](https://www.arangodb.com/docs/stable/indexing-ttl.html).

A linking operation can check sponsorship records with the TTL field for a matching contextid, and if there is one, it can remove the TTL field to make it permanent, and then create the operation to forward the sponsor operation (using the userid instead of the contextid). Only at this point will the sponsorship be considered used.

This way a user's verification can be checked as soon as they're linked without having to link first, wait, sponsor, wait, then check for the verification.

This is already done by on-chain event checks because the sponsorship updater looks back several blocks when looking for sponsor events--so sponsoring can be done before linking. This change would allow node API sponsoring operations to accomplish the same thing.  If we implement what's described above, the sponsorship updater won't need to look back several blocks (unless it's easier to do it that way.)

@siftal @abramsymons see if you find any problems with this approach.

**Comment by abramsymons** [comment]
Everything seems fine to me.
