### ISSUE TITLE
Add webhooks to enable apps getting notified when when a contextId is linked or sponsored

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#182]
Having webhooks for apps to get notified when a contextId is linked or sponsored makes app integration simpler for developers and reduce wasting of resources for polling server.

- To enable apps using webhooks, a new service should be added to the node to monitor `Link ContextId` and `Sponsor` operations send notifications to apps that defined endpoints for receiving them.
- One column can be added to the apps spreadsheet to define the endpoint that apps want notifications to be sent to.
- In decentralized BrightID network case it does not make sense to get notifications from multiple nodes and apps should define which node they want to get notifications from. Another columns can be added to the apps spreadsheet to enable them setting the public key of the node they want to get notifications from.
- Notifications should be signed by nodes private keys and apps should verify signatures to ensure notifications are sent from the requested node.
- If the request from node to the app endpoint failed because of problems on app side, node will retry 8 more times in 1, 2, 4, 8, 16, 32, 64, 128 minutes.

**Comment by adamstallard** [comment]
> * One column can be added to the apps spreadsheet to define the endpoint that apps want notifications to be sent to.
> 
> * In decentralized BrightID network case it does not make sense to get notifications from multiple nodes and apps should define which node they want to get notifications from. Another columns can be added to the apps spreadsheet to enable them setting the public key of the node they want to get notifications from.
> 
> * Notifications should be signed by nodes private keys and apps should verify signatures to ensure notifications are sent from the requested node.
>

Why not have an api endpoint that allows a client to register a webhook with a node? This is how most APIs do it.

**Comment by siftal** [comment]
> Why not have an api endpoint that allows a client to register a webhook with a node? This is how most APIs do it.

we should have an API endpoint to enable app owners to register apps and also edit their attributes including the webhook url.

**Comment by siftal** [comment]
notifying apps on sponsorship seems not helpful and notifying apps on linking is implemented [here](https://github.com/BrightID/BrightID/issues/958) on the client side.
implementation of this feature on the client side automatically resolves the issue of configuring which node should notify the app in the decentralized network. in the implemented approach, the client that links notifies the app.
