### ISSUE TITLE
Special categories of people such as attorneys

### ISSUE THREAD

**Issue by vporton** [BrightID/BrightID-Node#187]
Probably, we need some kind of special support of "attorneys" - specifically "authorized" users that are marked to have special permissions.

For example, the votes of three identified people may be enough to transfer $10000 but the votes of three attorneys are enough to transfer $1000000. Something like this. Please discuss.

**Comment by adamstallard** [comment]
A better place to discuss proposals is [our forum](https://forum.brightid.org/).  I'll close this issue now.
