### ISSUE TITLE
Adding a "recovery-level2" verification

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#204]
@castall suggested:

I think the next level to that verification will be to follow the edges in the graph between only those nodes that have the basic "SocialRecoverySetup" verification--starting from seeds, and allowing trust to flow through directed recovery connections.  We could call this recovery-level2 or recovery-plus-seed.  I'm hoping this can be a strong verification that is harder to get, but achievable by many people.  I can see it being a useful alternative for new applications in addition or instead of "level 0" (what we now call "brightid").

This verification comes from a seed selecting someone as a recovery connection and then following that for some number of hops.

A seed is someone that we pre-trust. If we trust them it means they value their BrightID and intend to use it.  This means they care about setting up social recovery correctly (so they don't lose their BrightID).  This means that the people they select as recovery should also tend to be trustworthy.  So you get transitive trust.
The weakness is that you could set up social recovery correctly to protect yourself, but then add some of your own sybils as extra recovery connections.
For that reason, it makes sense to combine that verification with others that measure other types of connections, but it's a good start.

**Comment by siftal** [comment]
`Bitu` and `Aura` will be the next level of verification and this proposal is out of date.
