### ISSUE TITLE
Enable apps to choose if they want to sponsor not verified users

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#209]
Currently not verified users can be sponsored by apps.
@castall suggested some apps may be interested in such a feature to enable them having more sponsored users and being shown in higher position in list of apps.
Some apps on the other side may not to be interested because spending apps sponsorships for not verified users can be very costly and may also open some sort of attack vectors to their resources.
We can add a new attribute to apps like `onlySponsorVerified` to enable apps choose which approach they prefer to follow.

**Comment by siftal** [comment]
https://github.com/BrightID/BrightID/issues/1063
