### ISSUE TITLE
Allow users to decide how many "recovery connections" are needed to recover their BrightID

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID-Node#211]
Copied from https://github.com/BrightID/BrightID/issues/753:

> Currently, 2 recovery connections are needed to recover a BrightID account.
Some users might find it not secure enough and want to have a higher number of recovery connections for recovering their account.

I like this idea, but it requires backend support.

@adamstallard @abramsymons What do you think?

**Comment by adamstallard** [comment]
> 
> 
> Copied from [BrightID/BrightID#753](https://github.com/BrightID/BrightID/issues/753):
> 
> > Currently, 2 recovery connections are needed to recover a BrightID account.
> > Some users might find it not secure enough and want to have a higher number of recovery connections for recovering their account.
> 
> I like this idea, but it requires backend support.
> 
> @adamstallard @abramsymons What do you think?

I think it's a good idea, but not high priority because 2 of N is a pretty good default.
