### ISSUE TITLE
Apps in testing mode should also be returned to clients

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#218]
Not returning apps in testing mode to clients result in user failure in linking contextId for those apps because clients are checking if context is valid based on list of contexts they have for apps.
To prevent this, nodes should return testing apps to client, but client should filter those when showing apps list.

**Comment by adamstallard** [comment]
If I understand correctly, a tester won't be able to test linking using their BrightID mobile reference app because testing apps aren't returned under the `/apps` endpoint

**Comment by adamstallard** [comment]
The context is in the deep link, so why does it need to be retrieved from the node?

**Comment by adamstallard** [comment]
If we update just the node backend to include `testing` apps, at least we can leave the `testing` box checked and they won't show up on https://apps.brightid.org , even if they show up in the mobile reference app apps tab.

**Comment by adamstallard** [comment]
@siftal @abramsymons Is there a reason we can't release this? There are some apps that want to be able to test without showing up on the apps page.

**Comment by adamstallard** [comment]
@siftal I think we also need to add `testing` to the return from `AppToDic` https://github.com/BrightID/BrightID-Node/blob/f555c6f95dd185842f10156f151c6d0612ddcb83/web_services/foxx/brightid/db.js#L540-L552
