### ISSUE TITLE
Increasing number of operations a single node can relay per second

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#221]
It seems node one can only relay 10-12 operation per block.
Considering the fact that having more nodes to relay operations can make the network scalable, the question is that how can we improve `consensus_sender` to relay operations faster?

**Comment by adamstallard** [comment]
> 
> 
> It seems node one can only relay 10-12 operation per block.
> Considering the fact that having more nodes to relay operations can make the network scalable, the question is that how can we improve `consensus_sender` to relay operations faster?

If I understand correctly, the problem is with BrightID, not IDChain.  We're not running into a block gas limit or any other IDChain limit.  Is this correct?

**Comment by abramsymons** [comment]
> > It seems node one can only relay 10-12 operation per block.
> > Considering the fact that having more nodes to relay operations can make the network scalable, the question is that how can we improve `consensus_sender` to relay operations faster?
> 
> If I understand correctly, the problem is with BrightID, not IDChain. We're not running into a block gas limit or any other IDChain limit. Is this correct?

yes, you're right.

**Comment by siftal** [comment]
It is solved by using batch operation sending
