### ISSUE TITLE
add nodes' public signing key in the response of the GET ''/state" and on the applications page

### ISSUE THREAD

**Issue by siftal** [BrightID/BrightID-Node#247]

**Comment by adamstallard** [comment]
Could we list the public part of the node's signing key on https://app.brightid.org/node/v5/state ?  Ideally, to support key rotation, a node should be able to list valid keys and revoked keys on its state endpoint

**Comment by abramsymons** [comment]
public keys are listed here in response of `/v6/state` now.
http://node.brightid.org/brightid/v6/state
why " revoked keys" are important to be listed? @adamstallard

**Comment by adamstallard** [comment]
> why " revoked keys" are important to be listed? @adamstallard

It doesn't seem important
