### ISSUE TITLE
add an endpoint to add a verification for a test user

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#263]
Add an endpoint that can be enabled manually via editing `config.env` to enable client devs or apps devs to add a specific verification to their test users on the test server.

**Comment by siftal** [comment]
instead of adding an endpoint, we added a query param (pseudoVerification) which client devs or apps devs can use to get pseudo verification when the node is in the development mode (development mode enable manually via editing config.env)
