### ISSUE TITLE
Linking a contextId that's too long makes `signed=eth` unusable for other contextIds

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#276]
We either need a way to support contextIds longer than 32 bytes for `signed=eth` or just omit ones that are too long when the `signed=eth` parameter is applied.  If the smart contract can't handle contextIds larger than 32 bytes, then it's ok to omit from the array returned because they could not have ever been added to the smart contract.  This is certainly better than permanently breaking the `signed=eth` functionality for that BrightID user.

Repro:

https://app.brightid.org/node/v5/verifications/soulbound/abc
```
{
  "data": {
    "unique": false,
    "app": "soulbound",
    "context": "soulbound",
    "contextIds": [
      "waytoolongwaytoolongwaytoolongwaytoolong",
      "abc"
    ]
  }
}
```
https://app.brightid.org/node/v5/verifications/soulbound/abc?signed=eth
```
{
  "error": true,
  "errorNum": 500,
  "errorMessage": "Invalid count value",
  "code": 500
}
```

**Comment by siftal** [comment]
If an app is `soulbound`, we prevent users from linking contextIds that are longer than 32 bytes.
Allowing users to link a long contextId and then omitting it when getting verification seems to be a risky and not a secure approach. Apps are generating contextIds and if they need to use `eth` signatures, they should not generate long contextIds for their users.
