### ISSUE TITLE
Assigning scores

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#31]
The scores for each group in SybilGroupRank need to be converted into something that makes sense.

The sybilRank paper says this

>an
OSN cannot simply identify a pivot in the ranked list below
which all nodes are fake, and it still has to rely on
manual inspection.

but they are considering graphs that already exist.  If we look at how the graph changes between iterations--starting from a graph that is completely honest, we can assign probabilities to ranges, by assuming that honest users can improve their scores, while sybils can't.

New users can start with low scores, but they can improve.  We can find good probability boundaries by making the assumption that sybils' scores won't improve.

Rather than storing scores twice, we can store just the raw ranks from sybilGroupRank, and then store a mapping that sets the probability boundaries (there could be 10 or 100 boundaries, for instance). These boundaries are adjusted after each iteration of sybilGroupRank. To get a group's score requires looking up the raw ranks, looking up the boundary map, and making the conversion at query time.

**Comment by abramsymons** [comment]
so the first thing we have to do is to save raw ranks instead of normalized ranks. I will do that today.

secondly, if i'm not mistaken, you intend to adjust the boundries manually in each iteration by relying on the scores that known honests (seeds?) have gained.

Accordingly, these calculations are not done on anti_sybil codes that are implemented in python. They are done on the API side at the time of reading in the nodejs on the backend. is that right?

**Comment by adamstallard** [comment]
They boundaries should be adjusted every time sybilgrouprank is run.  They can be persisted somewhere where the node can access them (as part of serving a request for a score)--the DB makes sense.

As far the boundary-setting function, I'll create a document we can work on together.  https://docs.google.com/document/d/1sGZeivcVFUiT9erYKmo07w98GZ0pkTWLWrsF5I3XJTA/edit?usp=sharing

**Comment by abramsymons** [comment]
> boundaries should be adjusted every time sybilgrouprank is run.
manually? or by a script looking at seed group scores for example?
> They can be persisted somewhere where the node can access them (as part of serving a request for a score)--the DB makes sense.
I can simply add a script just like label_seed_groups.py to read a csv file listing boundaries and fill a collection we define for saving boundaries.

**Comment by abramsymons** [comment]
I was reading the first comment again and I think we should clarify what we mean from the "boundaries map" term. Do we mean a map between ranges of raw ranks of each group and the probability of being honest if someone score be in that range? Or we mean a map between ranges of raw ranks and normalized ranks?

It seems you mean first one. But what we should finally achieve for distribution, save in database and use at query time to return normalized score is the second.

The goal from normalization is to convert raw scores gained from sybilrank algorithm to new normalized scores which make our honest community scores distributed like attached image.

For example if we suppose -3, 0, 3 in this image are 0, 50 and 100, we should give a normalized score to our users in a way that 68% of honest users get a score between 33 and 66.

![normal-distrubution-large](https://user-images.githubusercontent.com/36688816/46514707-be99d100-c85f-11e8-9412-0e1212971e4b.png)

**Comment by adamstallard** [comment]
"Normalization" was probably a poor word choice on my part.

Let me explain what we want to end up with.  We want a score that clearly communicates something to application providers.  What we want to communicate is this:

If you choose a score of 90 (of 100) you are saying you can tolerate 1 in 10 users being sybils.  If you choose a score of 50 (of 100) you are saying you can tolerate half of your users being sybils. If you choose a score of 20, you are saying you can tolerate only 1 in 5 users being a real person.

What we really want scores to mean is "sybil tolerance."  The scores are used by applications, and they are the ones that need to have an idea what they mean.  To an end-user all they know is "higher is better" and it's easy to come up with a system that achieves that.  To create a score that communicates sybil tolerance effectively to applications is our challenge.

**Comment by abramsymons** [comment]
> "Normalization" was probably a poor word choice on my part.

my goal in implementing that normalization was to spread close users in dense areas to an extend enough to distinguish them.

The approach you are offering here seems to be very useful to act as the logic for distributing the ranks.

**Comment by adamstallard** [comment]
Right. From a perspective of utility for the app providers, it's fine if the majority of users have the same score.  80% of users could all have the highest score, and that could be fine, possibly even preferable for app providers.

The goals are laid out here (which you've seen and commented on):  https://docs.google.com/document/d/1sGZeivcVFUiT9erYKmo07w98GZ0pkTWLWrsF5I3XJTA/edit?usp=sharing

I renamed the document "Assigning Scores."

**Comment by adamstallard** [comment]
Closing now that we're using "verifications."
