### ISSUE TITLE
automate app registry

### ISSUE THREAD

**Issue by siftal** [BrightID/BrightID-Node#314]
Currently creating and updating an app must be done manually by operators, but we can have a service to enable app owners to add, remove or modify apps themselves.

- Authentication can be done using a key pair.
- New apps will be added in testing mode and BrightID super admin can change the mode of the apps by updating the spreadsheet.
- Inactive testing apps should be removed periodically.
- Creating a bunch of fake apps can overload BrightID nodes. The right approach to prevent this seems to be having a fee for the creation of apps in one of the following forms:
  - Pay BrightID DAO some Bright token
  - Burn some Bright token
  - Assign some Sp to the app

[issue #80](https://github.com/BrightID/BrightID-Node/issues/80) should be considered in implementation.

**Comment by siftal** [comment]
Adds an API used to register/remove/update apps by the app owners
https://github.com/BrightID/BrightID-Apps-Page/commit/51e1dfb8c06c05b6de33d0447247af1d22b9bbca

**Comment by adamstallard** [comment]
> * Pay BrightID DAO some Bright token
> 
> * Burn some Bright token
> 
> * Assign some Sp to the app

Which of these approaches do you like the best @siftal ?  Checking for assigned Sp is probably the easiest for us.

**Comment by adamstallard** [comment]
> Adds an API used to register/remove/update apps by the app owners [BrightID/BrightID-Apps-Page@51e1dfb](https://github.com/BrightID/BrightID-Apps-Page/commit/51e1dfb8c06c05b6de33d0447247af1d22b9bbca)

Nice!  Is there any documentation for this?
