### ISSUE TITLE
Create regular DB dumps

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#39]

**Comment by adamstallard** [comment]
Create them and host them (ideally on from a different server for redundancy)

**Comment by adamstallard** [comment]
Could be done with a cron in the db container that then puts them in a docker volume

**Comment by adamstallard** [comment]
There is some intermediate code to support this in this commit b39ad0833096fe94a70eebd625dbf4b1489c0b12

**Comment by DrewGregory** [comment]
Where do you think the backup should be hosted remotely? another node? would it make sense to add functionality so that nodes can create backups and/or download other backups and host backups themselves?

**Comment by adamstallard** [comment]
I don't know where backups should be publicly hosted.  Let's provide node operators with instructions on how to manage the backups that are saved on their node, and they can make that decision for themselves. I think for us (node one), I would host them on cheap cloud storage and have a dns name pointing to it.  Maybe ipfs is another option.

At some point, there will need to be a standard way of retrieving and applying the most recent backup for new node operators, and by then there will need to be a recommended way to host backups, but that's not what this issue is about.

**Comment by adamstallard** [comment]
There could be a new foxx app (not BrightID) just for downloading the (compressed tar) file if that's easier than downloading the file from docker.  It would not be public, though. Figuring out how to publicly host these files is beyond the scope of the issue.
