### ISSUE TITLE
Backup operation sets

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#40]
related to #38

**Comment by adamstallard** [comment]
This could be used as an incremental backup to replay operations after a database dump is restored.

**Comment by adamstallard** [comment]
Backed up operation sets should have an accompanying file with signatures from all nodes that endorse the operation set.

**Comment by abramsymons** [comment]
We have a collection for operations on the nodes.
We can backup operations in the predefined periods that we use for getting snapshot from the system for scorer, and clear operations for example older than one day.
What should we do with these backup of operations (operation sets)? can you explain more about this please:

> Backed up operation sets should have an accompanying file with signatures from all nodes that endorse the operation set.

**Comment by adamstallard** [comment]
> We have a collection for operations on the nodes.
> We can backup operations in the predefined periods that we use for getting snapshot from the system for scorer, and clear operations for example older than one day.
> What should we do with these backup of operations (operation sets)? can you explain more about this please @adamstallard :
> 
> > Backed up operation sets should have an accompanying file with signatures from all nodes that endorse the operation set.

What I mean is that when you publish a backup file you can also publish another file that has the hash of the file to use a checksum, then in the same file with the hash, the node can provide a signature of that checksum with its private key so that anyone can verify that the node has endorsed that backup file.
