### ISSUE TITLE
Downloadable application for simulating sybil attacks

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#41]
I was thinking today about how other people can easily run simulations to help us improve our anti-sybil system.

I really like the web-based sybil attack simulator you built.

We are going to start taking regular backups (dumps) of the graph.  What I would like is for any user to run the sybil attack simulator on a recent dump of the graph. If the graph starts getting too big, we can create a utility that dumps smaller subsets of the graph to make a simulation more manageable.

I think we could use the same stack: html, javascript, python, but create an installer (or docker solution) that runs everything locally on a user's machine. The application can know where to download graph dumps from a site where we host them.

This way a user can experiment with different graphs loaded from arangodb running on their own machine.  Multiple users can operate on different graphs without bogging down our test machine with having to load multiple copies (dumps) of the graph in arangodb.

We can offer bounties to users that submit a simulation that leads to an improvement in the anti-sybil system.

**Comment by abramsymons** [comment]
I try to complete this in 2-3 days.

**Comment by abramsymons** [comment]
Should this issue be closed? @adamstallard 
We have instructions to locally run the web based service here:
https://github.com/BrightID/BrightID-AntiSybil
I tested that just now with `pip install anti_sybil` and opening `localhost:8082` with browser. 
It also has a load graph section where you can upload db dump files.
