### ISSUE TITLE
Adding name of operation to all messages that are signed by clients

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#58]
For each operation, there is a message that is signed by brightid user and sent to the node which verify the message and apply that to its database. These messages has fields like brightid of the user, timestamps of the request, and some other parameters like brightid of the friend for connection request or id of the group for joining a group.

Currently There is no field in those messages indicating the operation which is requested and signed by the user. In fact we are relying on difference of parameters for different operations to separate those messages.

Such approach is risky because if some different operations have similar parameters, the signature which is generated for one operation can be used by bad actor to run another operation on nodes.

For example currently the parameters for creating a group and deleting that are the same. It's not a serious problem as only new groups which are not completely funded by 3 members can be deleted.

To avoid such conflicts in the future, it's better to add operation name to all messages signed by clients.

**Comment by adamstallard** [comment]
@abramsymons is this still open?

**Comment by abramsymons** [comment]
no
