### ISSUE TITLE
Manage api version routing through nginx

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#69]
Currently we use

`/brightid/` after the host name as the beginning of a call to the brightid api.  This is fine, since the nodes may host other things, and we don't yet have instructions for how they should configure their dns.

Foxx will be serving `/brightid` (i.e. v1 backend) and `/brightid3` simultaneously.  This will give us time to release the backend first.

For requests from the v3 frontend, we should add something to route it to `/brightid3`  this should be either a custom request header:
```
Accept-version: 3
```
Or an extra segement in the url:
```
/brightid/v3/
```
Nginx can route requests to `/brightid3` based on either one of those.

Once the v3 frontend is released, we will take down `/brightid` from Foxx.

If we want we can have nginx return the message: "Please upgrade your mobile app to the latest version." to every request to `/brightid` that doesn't specify `Accept-version: 3` or include the `v3` path segment.

A future release of the application should make version 3 the default so that if no `Accept-version: 3` (or `/v3` path segment) is included, it will still route to `/brightid3` in foxx.  We will release this after we've given everyone enough time to upgrade their mobile app.

So which do you prefer for the frontend?

a custom request header:
```
Accept-version: 3
```
Or an extra segement in the url:
```
/brightid/v3/
```

**Comment by abramsymons** [comment]
I updated foxx in v3 branch to be installed on /brightid3

**Comment by abramsymons** [comment]
I prefer `/brightid/v3/` because it's more clear and we can simply test endpoints in the browser without need to provide headers.

**Comment by adamstallard** [comment]
> I updated foxx in v3 branch to be installed on /brightid3 and also updated nginx configuration to point /brightid to that.
> Should we add the v1 installation on /brightid to the [docker-entrypoint.sh](https://github.com/BrightID/BrightID-Node/blob/v3/web_services/docker-entrypoint.sh) too?

Yes, we need v1 and v3 to both be deployed. At first everyone will be using v1, then everyone will be using v3. The switch will happen when new versions of the frontend hit the app stores.

**Comment by adamstallard** [comment]
Do you still need to deploy this foxx "app" in docker-entrypoint.sh

```
foxx upgrade /apply /code/foxx/apply_1.0.0.zip ||
foxx install /apply /code/foxx/apply_1.0.0.zip
```

It seems to move /brightid3 to /brightid

**Comment by adamstallard** [comment]
>I updated foxx in v3 branch to be installed on /brightid3 and also updated nginx configuration to point /brightid to that.

`/brightid/v3` should direct to `/brightid3` and `/brightid` should direct to `/brightid`

Later, we will change the default version to be v3 and `/brightid` can direct to `/brightid3` .  For now the default needs to be v1 because there are still v1 frontend users.

**Comment by abramsymons** [comment]
> Do you still need to deploy this foxx "app" in [docker-entrypoint.sh](https://github.com/BrightID/BrightID-Node/blob/v3/web_services/docker-entrypoint.sh)
> 
> ```
> foxx upgrade /apply /code/foxx/apply_1.0.0.zip ||
> foxx install /apply /code/foxx/apply_1.0.0.zip
> ```
> 
> It seems to move /brightid3 to /brightid

This foxx service is nothing to do with brightid service. The apply service will be used by the consensus module to apply operations to the database and is not visible to outside.

**Comment by adamstallard** [comment]
> > Do you still need to deploy this foxx "app" in [docker-entrypoint.sh](https://github.com/BrightID/BrightID-Node/blob/v3/web_services/docker-entrypoint.sh)
> > ```
> > foxx upgrade /apply /code/foxx/apply_1.0.0.zip ||
> > foxx install /apply /code/foxx/apply_1.0.0.zip
> > ```
> > 
> > 
> > It seems to move /brightid3 to /brightid
> 
> This foxx service is nothing to do with brightid service. The apply service will be used by the consensus module to apply operations to the database and is not visible to outside.

Thanks for the clarification. Could the code (not just the zip) be added to the repo?

I think what confused me as to the purpose of this app is the "deploy.sh" script:
```
rm -rf ../brightid_3.0.0.zip
zip -r ../brightid_3.0.0.zip .
foxx uninstall /brightid
foxx install /brightid ../brightid_3.0.0.zip
```

Based on what you said, it seems this file should be removed.
