### ISSUE TITLE
Deploy DB Schema to Prod

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID-Node#70]
These are collections we had in last release of v1:

`users, connections, removed, groups, newGroups, usersInGroups, usersInNewGroups, contexts, sponsorships`

The `removed` is deprecated in v3, and we have `operations`, `operationsHashes` and `variables` added.

**Comment by abramsymons** [comment]
In v3 we have `signingKey` and 'createdAt` added to the `users` collections that should be set for all users created by v1 code.

Not setting them don't make any serious problems.

For `signingKey` we are using [this code](https://github.com/BrightID/BrightID-Node/blob/v3/web_services/foxx/brightid_3.0.0/operations.js#L21) to verify signatures so there is no problem for old users;
For `createdAt` I think the only problem will be that we see NaN or such thing in [new connection preview screen](https://github.com/BrightID/BrightID/blob/49a29c219be7dd5f296642c7a476a1168d5ff28a/BrightID/src/components/NewConnectionsScreens/PreviewConnectionScreen.js#L67) as creation time of user.

I think the best approach is to run 2 queries on users collections to set these attributes on all users now and also when we close the v1 api.

**Comment by abramsymons** [comment]
v3 docker file of db service gets the latest database dump from the google storage, restore that and start reading operations after the last operation applied to that backup from the chain and apply them.

This works for all nodes that join the network after the first node to the brighttid network if we have the first node running and saving daily backups in the google storage.

But what is our approach for releasing the first node?


1) I think we should shut down the web service
2) Add `operations` and `operationHashes`
3) Stop backup service on test.brightid.org and run that on node.brightid.org to upload brightid.tar.gz with these two collections and last data to google storage.
4) Stop all services including db on the node.brightid.org and build the new images and run the containers.

**Comment by adamstallard** [comment]
> v3 docker file of db service gets the latest database dump from the google storage, restore that and start reading operations after the last operation applied to that backup from the chain and apply them.
> 
> This works for all nodes that join the network after the first node to the brighttid network if we have the first node running and saving daily backups in the google storage.
> 
> But what is our approach for releasing the first node?
> 
> 1. I think we should shut down the web service
> 2. Add `operations` and `operationHashes`
> 3. Stop backup service on test.brightid.org and run that on node.brightid.org to upload brightid.tar.gz with these two collections and last data to google storage.
> 4. Stop all services including db on the node.brightid.org and build the new images and run the containers.

Let's talk about a release strategy for V3 somewhere else.  This is issue is about deploying a new DB schema to Prod.
