### ISSUE TITLE
Read sponsorships from the BrightID smart contract

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID-Node#79]
With https://github.com/BrightID/BrightID-SmartContract/issues/4 , it's possible to sponsor through the BrightID smart contract.  A BrightID Node should read those (either through even logs or contract data) and make sure they are added to the Sponsorships collection.

**Comment by adamstallard** [comment]
This could be done as part of the sp_updater process

**Comment by auryn-macmillan** [comment]
What is the effort on this issue? Just so I can throw it in the colony.

**Comment by adamstallard** [comment]
It's just going to be done very soon by our core team
