### ISSUE TITLE
Allow dismissing of admins from group

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID-Node#98]
We want to allow group admins to remove other group admins. Current implementation of `dismiss` operation does not allow this.

**Comment by adamstallard** [comment]
Can we generalize this to remove any member from a group? If enough regular members become unreachable, the group also becomes useless due to the >50% connection rule for joining.

**Comment by TripleSpeeder** [comment]
> Can we generalize this to remove any member from a group? If enough regular members become unreachable, the group also becomes useless due to the >50% connection rule for joining.

I think normal users can already be removed. There is just a check in place that prevents admins from being removed. See `function dismiss(dismisser, dismissee, groupId, timestamp)` in `db.js`

**Comment by TripleSpeeder** [comment]
Implemented by @abramsymons in 1861ced51bb7daad0c0490422aa846381f630814
